fragment UserFields on User {
  id
  nickname
}

fragment ReleaseFields on Release {
  id
  title
  releaseType
  addedOn
  inInbox
  inFavorites
  releaseYear
  releaseDate
  rating
  numTracks
  runtime
  imageId

  artists {
    artist {
      id
      name
    }
    role
  }

  genres {
    id
    name
  }
}

fragment ArtistFields on Artist {
  id
  name
  starred
  numReleases
  imageId
}

fragment CollectionFields on Collection {
  id
  name
  starred
  type
  numReleases
  lastUpdatedOn
  imageId

  user {
    ...UserFields
  }
}

fragment InviteFields on Invite {
  id
  code
  createdBy {
    ...UserFields
  }
  createdAt
  usedBy {
    ...UserFields
  }
}

fragment PlaylistFields on Playlist {
  id
  name
  starred
  type
  numTracks
  lastUpdatedOn
  imageId

  user {
    ...UserFields
  }
}

fragment TrackFields on Track {
  id
  title
  duration
  trackNumber
  discNumber
  inFavorites

  release {
    id
    imageId
  }

  artists {
    artist {
      id
      name
    }
    role
  }
}

fragment FullReleaseFields on Release {
  ...ReleaseFields

  collages {
    id
    name
  }

  labels {
    id
    name
  }

  tracks {
    ...TrackFields
  }
}
