# This docker-compose file is for local development. For a production
# docker-compose file, refer to the documentation's Installation page.

version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./backend:/app/backend
      - ./data:/data
      - ./testlib:/music
  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./data:/data
      - ./testlib:/music
