
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='repertoire',
    version='0.1.0',
    description='A release-oriented music server.',
    python_requires='==3.*,>=3.6.0',
    author='azuline',
    author_email='azuline@riseup.net',
    license='AGPL-3.0',
    entry_points={"console_scripts": ["repertoire = backend.__main__:run"]},
    packages=['backend', 'backend.cli', 'backend.lib'],
    package_dir={"": "."},
    package_data={"backend": ["migrations/*.sql", "tests/data/*.ini"]},
    install_requires=['backports-datetime-fromisoformat==1.*,>=1.0.0', 'click==7.*,>=7.1.0', 'daemonize==2.*,>=2.5.0', 'flask==1.*,>=1.1.0', 'gevent==20.*,>=20.6.0', 'huey==2.*,>=2.3.0', 'pillow==7.*,>=7.2.0', 'python-dotenv==0.*,>=0.14.0', 'requests==2.*,>=2.24.0', 'tagfiles==0.*,>=0.3.1', 'unidecode==1.*,>=1.1.1', 'voluptuous==0.*,>=0.11.7', 'yoyo-migrations==7.*,>=7.2.0'],
    extras_require={"dev": ["black==20.8b1", "flake8==3.*,>=3.8.0", "flask-cors==3.*,>=3.0.8", "isort==5.*,>=5.4.0", "pytest==6.*,>=6.1.1", "pytest-cov==2.*,>=2.10.1"]},
)
