
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='repertoire',
    version='0.1.0',
    description='A release-oriented music server.',
    python_requires='==3.*,>=3.7.0',
    author='azuline',
    author_email='azuline@riseup.net',
    license='AGPL-3.0',
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=['python-dotenv==0.*,>=0.14.0', 'requests==2.*,>=2.24.0', 'selectolax==0.*,>=0.2.7', 'tagfiles==0.*,>=0.3.0'],
    extras_require={"dev": ["black==20.8b1", "flake8==3.*,>=3.8.0", "isort==5.*,>=5.4.0"]},
)
