[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["blissful <blissful@sunsetglow.net>"]

[tool.poetry.dependencies]
python = "^3.8"
Jinja2 = "^2.11.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
