name: 'Setup Backend'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9.1'
    - uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: 1.1.4
    - name: Cache dependencies.
      id: cache-deps
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies.
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: poetry install
