name: Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend/'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: abatilo/actions-poetry@v2.1.0
      - name: Cache dependencies.
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies.
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: poetry install
      - name: Run tests.
        run: poetry run pytest --cov-report=xml --cov=. --cov-branch tests/
      - name: Upload coverage.
        run: bash <(curl -s https://codecov.io/bash) -cF python

  type_check:
    name: Type check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend/'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: abatilo/actions-poetry@v2.1.0
      - name: Cache dependencies.
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies.
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: poetry install
      - name: Run type check.
        run: poetry run mypy src/

  lint_check:
    name: Lint check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend/'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: abatilo/actions-poetry@v2.1.0
      - name: Cache dependencies.
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies.
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: poetry install
      - name: Run lint check.
        run: |
          poetry run black --check .
          poetry run isort -c .
          poetry run flake8 .

  schema:
    name: Schema
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend/'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: abatilo/actions-poetry@v2.1.0
      - name: Cache dependencies.
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies.
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: poetry install
      - name: Diff schema.sql and generated schema.
        run: |
          mv schema.sql schema.sql.old
          mkdir ../data
          make schema
          diff schema.sql.old schema.sql
