name: Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend/'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-backend
      - name: Run tests.
        run: poetry run pytest --cov-report=xml --cov=. --cov-branch tests/
      - name: Upload coverage.
        run: bash <(curl -s https://codecov.io/bash) -cF python

  type_check:
    name: Type check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend/'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-backend
      - name: Run type check.
        run: make typecheck

  lint_check:
    name: Lint check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend/'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-backend
      - name: Run lint check.
        run: make lintcheck

  schema:
    name: Schema
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend/'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-backend
      - name: Generate schema.
        run: make schema
      - name: Check for dirty files.
        run: bash -c '[[ -z $(git status -s) ]] || (exit 1)'

  setupfiles:
    name: Setupfiles
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend/'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-backend
      - name: Generate setupfiles.
        run: make setupfiles
      - name: Check for dirty files.
        run: bash -c '[[ -z $(git status -s) ]] || (exit 1)'
