name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: abatilo/actions-poetry@v2.1.0

      - name: Install backend dependencies.
        run: |
          cd backend
          poetry install

      - name: Run backend tests.
        run: |
          cd backend
          poetry run pytest --cov-report=xml --cov=. --cov-branch tests/

      - name: Run backend lint check.
        run: |
          cd backend
          poetry run black --check .
          poetry run isort -c .
          poetry run flake8 .

      - name: Upload coverage.
        run: bash <(curl -s https://codecov.io/bash) -cF python
