name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: abatilo/actions-poetry@v2.1.0

      - name: Install dependencies.
        run: poetry install

      - name: Run tests.
        run: poetry run pytest --cov-report=xml --cov=backend --cov-branch backend/tests

      - name: Run lint check.
        run: |
          poetry run black --check backend/
          poetry run isort -c backend/
          poetry run flake8 backend/

      - name: Upload coverage.
        run: bash <(curl -s https://codecov.io/bash) -cF python
