name: Frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  type_check:
    name: Type check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend/'
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies.
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies.
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install
      - name: Run type check.
        run: yarn tsc

  lint_check:
    name: Lint check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend/'
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies.
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies.
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install
      - name: Run lint check.
        run: yarn eslint src/ --ext .ts,.tsx --max-warnings=0
