name: Frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  type_check:
    name: Type check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend/'
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies.
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies.
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: CI=true yarn install
      - name: Run type check.
        run: CI=true yarn tsc

  lint_check:
    name: Lint check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend/'
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies.
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies.
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: CI=true yarn install
      - name: Run lint check.
        run: CI=true yarn eslint src/ --ext .ts,.tsx --max-warnings=0

  gql_codegen:
    name: GraphQL Codegen
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend/'
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies.
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies.
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: CI=true yarn install
      - name: Run codegen.
        run: CI=true yarn codegen
      - name: Check for dirty files.
        run: bash -c '[[ -z $(git status -s) ]] || (exit 1)'
